### ISSUE TITLE
TypeError: this._throw is not a function

### ISSUE THREAD

**Issue by SethConnell** [wagenaartje/stocks.js#18] opened 2018-09-22 01:23 UTC
Any time I enter an incorrect stock symbol, I get this error:

`TypeError: this._throw is not a function`

Yet it still works when I give a correct stock symbol. Do you know how I can resolve this issue?

**Comment by kvadd** [comment] 2018-10-04 11:09
I got the same issue here. The issue is that the this scope is not working properly under the promise. This can be fixed by either referencing the proper root this, or you can just comment out the error handling and wrapping your code into a try/catch block.

**Comment by davidsoederberg** [comment] 2018-10-06 19:15
I [forked](https://github.com/davidsoederberg/stocks.js) this repo and made changes to the error handling so you don't need to comment out the source code. I changed `this._throw(9, error);`  to `reject("No hit with your query")` on row [157](https://github.com/davidsoederberg/stocks.js/blob/da90a39c1581da83547a42364d805bb27222d1dd/dist/stocks.js#L157) in `dist/stocks.js`. This might not be the correct way to solve the problem but it seems to work for me. The error message might be bad aswell. Feel free to comment better solutions!
You can install this package with this little change using `npm install --save davidsoederberg/stocks.js`.

**Comment by SethConnell** [comment] 2018-10-07 06:09
> I [forked](https://github.com/davidsoederberg/stocks.js) this repo and made changes to the error handling so you don't need to comment out the source code. I changed `this._throw(9, error);` to `reject("No hit with your query")` on row [157](https://github.com/davidsoederberg/stocks.js/blob/da90a39c1581da83547a42364d805bb27222d1dd/dist/stocks.js#L157) in `dist/stocks.js`. This might not be the correct way to solve the problem but it seems to work for me. The error message might be bad aswell. Feel free to comment better solutions!
> You can install this package with this little change using `npm install --save davidsoederberg/stocks.js`.

Your solution is better than mine. I just wrote a separate script that checked if the stock quote was valid before passing it to stocks.js.

**Closed** 2020-08-09 13:27 UTC
